# Generated by Django 4.2.6 on 2023-10-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name': 'Detección', 'verbose_name_plural': 'Detecciones'},
        ),
        migrations.AlterModelOptions(
            name='pigeon',
            options={'verbose_name': 'Ave', 'verbose_name_plural': 'Aves'},
        ),
        migrations.AlterModelOptions(
            name='recognition',
            options={'verbose_name': 'Reconocimiento', 'verbose_name_plural': 'Reconocimientos'},
        ),
        migrations.AlterField(
            model_name='detection',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time of detection'),
        ),
    ]
